package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/neiromaster/enver/internal/config"
)

// writeTempConfig writes a single profile to a temp config file and returns its
// path. setDefault controls whether it becomes the default profile.
func writeTempConfig(t *testing.T, profile string, env map[string]string, comments map[string]string, setDefault bool) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "config.yaml")
	if err := config.UpsertProfile(path, profile, config.Profile{Env: env, Comments: comments}, setDefault, false); err != nil {
		t.Fatalf("UpsertProfile: %v", err)
	}
	return path
}

// withGlobalConfig sets globalFlags to point at path with local layering off and
// the write target on the global/config file, restoring previous values on
// cleanup. Use for tests that set up a single config file as the global config.
func withGlobalConfig(t *testing.T, path string) {
	t.Helper()
	savedConfig, savedNoLocal, savedGlobal := globalFlags.configPath, globalFlags.noLocal, globalFlags.global
	globalFlags.configPath = path
	globalFlags.noLocal = true
	globalFlags.global = true
	t.Cleanup(func() {
		globalFlags.configPath = savedConfig
		globalFlags.noLocal = savedNoLocal
		globalFlags.global = savedGlobal
	})
}

func TestRunDotenvStdout(t *testing.T) {
	path := writeTempConfig(t, "prod",
		map[string]string{"DB_HOST": "db.example.com", "API_TOKEN": "sk-live"},
		map[string]string{"DB_HOST": "Primary database host"}, true)
	withGlobalConfig(t, path)

	var out bytes.Buffer
	// Empty profile falls back to the default ("prod"); outPath "" → stdout; no confirm.
	if err := runDotenv(&out, "", "", false, false, nil); err != nil {
		t.Fatalf("runDotenv: %v", err)
	}
	s := out.String()
	if !strings.Contains(s, "# Generated by enver from profile \"prod\"") {
		t.Errorf("missing header:\n%s", s)
	}
	if !strings.Contains(s, "# Primary database host\nDB_HOST=db.example.com") {
		t.Errorf("missing commented var:\n%s", s)
	}
	if !strings.Contains(s, "API_TOKEN=sk-live") {
		t.Errorf("missing unmasked value:\n%s", s)
	}
	// Keys sorted alphabetically: API_TOKEN precedes DB_HOST.
	if ia, ib := strings.Index(s, "API_TOKEN="), strings.Index(s, "DB_HOST="); ia < 0 || ib < 0 || ia > ib {
		t.Errorf("keys not sorted:\n%s", s)
	}
}

func TestRunDotenvNoHeader(t *testing.T) {
	path := writeTempConfig(t, "p", map[string]string{"A": "1"}, nil, true)
	withGlobalConfig(t, path)

	var out bytes.Buffer
	if err := runDotenv(&out, "", "", true, false, nil); err != nil {
		t.Fatalf("runDotenv: %v", err)
	}
	if strings.Contains(out.String(), "Generated by enver") {
		t.Errorf("--no-header still emitted header:\n%s", out.String())
	}
}

func TestRunDotenvNoProfileNoDefaultError(t *testing.T) {
	path := writeTempConfig(t, "p", map[string]string{"A": "1"}, nil, false) // no default
	withGlobalConfig(t, path)

	var out bytes.Buffer
	err := runDotenv(&out, "", "", false, false, nil)
	if err == nil || !strings.Contains(err.Error(), "no profile specified") {
		t.Fatalf("expected no-profile error, got: %v", err)
	}
}

func TestRunDotenvUnknownProfileError(t *testing.T) {
	path := writeTempConfig(t, "p", map[string]string{"A": "1"}, nil, true)
	withGlobalConfig(t, path)

	var out bytes.Buffer
	if err := runDotenv(&out, "nope", "", false, false, nil); err == nil {
		t.Fatal("expected error for unknown profile")
	}
}

func TestWriteDotenvFileCreatesWith0600(t *testing.T) {
	path := filepath.Join(t.TempDir(), "out.env")
	var out bytes.Buffer
	if err := writeDotenvFile(&out, path, []byte("FOO=bar\n"), false, nil, 1, 0); err != nil {
		t.Fatalf("writeDotenvFile: %v", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	// Windows has no Unix permission bits; os.WriteFile's mode is not preserved.
	if runtime.GOOS != "windows" {
		if perm := info.Mode().Perm(); perm != 0o600 {
			t.Errorf("file mode = %o, want 0600", perm)
		}
	}
	got, err := os.ReadFile(path)
	if err != nil || string(got) != "FOO=bar\n" {
		t.Errorf("file contents = %q, err %v", string(got), err)
	}
	if !strings.Contains(out.String(), "✓ wrote out.env (1 vars)") {
		t.Errorf("missing confirmation line:\n%s", out.String())
	}
}

func TestWriteDotenvFileOverwriteConfirmed(t *testing.T) {
	path := filepath.Join(t.TempDir(), "e.env")
	if err := os.WriteFile(path, []byte("OLD=1\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	called := false
	confirm := func(msg string, def bool) (bool, error) {
		called = true
		if !strings.Contains(msg, "Overwrite") {
			t.Errorf("confirm prompt = %q, want Overwrite", msg)
		}
		return true, nil
	}
	if err := writeDotenvFile(&out, path, []byte("NEW=2\n"), false, confirm, 1, 0); err != nil {
		t.Fatalf("writeDotenvFile: %v", err)
	}
	if !called {
		t.Error("confirm was not called for existing file")
	}
	got, _ := os.ReadFile(path)
	if !strings.Contains(string(got), "NEW=2") {
		t.Errorf("file not overwritten:\n%s", string(got))
	}
}

func TestWriteDotenvFileOverwriteRefused(t *testing.T) {
	path := filepath.Join(t.TempDir(), "e.env")
	if err := os.WriteFile(path, []byte("OLD=1\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	refuse := func(string, bool) (bool, error) { return false, nil }
	if err := writeDotenvFile(&out, path, []byte("NEW=2\n"), false, refuse, 1, 0); err != nil {
		t.Fatalf("refuse should not error: %v", err)
	}
	got, _ := os.ReadFile(path)
	if string(got) != "OLD=1\n" {
		t.Errorf("file overwritten after refuse:\n%s", string(got))
	}
	if !strings.Contains(out.String(), "aborted") {
		t.Errorf("declined overwrite should print aborted:\n%s", out.String())
	}
	if strings.Contains(out.String(), "✓ wrote") {
		t.Error("confirmation printed after refuse")
	}
}

func TestWriteDotenvFileOverwriteNonInteractive(t *testing.T) {
	path := filepath.Join(t.TempDir(), "e.env")
	if err := os.WriteFile(path, []byte("OLD=1\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	broken := func(string, bool) (bool, error) { return false, io.EOF }
	err := writeDotenvFile(&out, path, []byte("NEW=2\n"), false, broken, 1, 0)
	if err == nil || !strings.Contains(err.Error(), "force") {
		t.Fatalf("non-interactive refusal should error with --force hint, got: %v", err)
	}
	got, _ := os.ReadFile(path)
	if string(got) != "OLD=1\n" {
		t.Errorf("file changed after non-interactive refusal:\n%s", string(got))
	}
	if strings.Contains(out.String(), "✓ wrote") {
		t.Error("confirmation printed after failed prompt")
	}
}

func TestWriteDotenvFileForceSkipsConfirm(t *testing.T) {
	path := filepath.Join(t.TempDir(), "e.env")
	if err := os.WriteFile(path, []byte("OLD=1\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	called := false
	never := func(string, bool) (bool, error) { called = true; return false, nil }
	if err := writeDotenvFile(&out, path, []byte("NEW=2\n"), true, never, 1, 0); err != nil {
		t.Fatalf("writeDotenvFile: %v", err)
	}
	if called {
		t.Error("confirm called under --force")
	}
	got, _ := os.ReadFile(path)
	if !strings.Contains(string(got), "NEW=2") {
		t.Errorf("file not force-overwritten:\n%s", string(got))
	}
}

func TestWriteDotenvFileEnforces0600OnOverwrite(t *testing.T) {
	path := filepath.Join(t.TempDir(), "e.env")
	if err := os.WriteFile(path, []byte("OLD=1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if err := writeDotenvFile(&out, path, []byte("NEW=2\n"), true, nil, 1, 0); err != nil {
		t.Fatalf("writeDotenvFile: %v", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if runtime.GOOS != "windows" {
		if perm := info.Mode().Perm(); perm != 0o600 {
			t.Errorf("file mode after overwrite = %o, want 0o600", perm)
		}
	}
}

func TestRunDotenvDoesNotExpand(t *testing.T) {
	path := writeTempConfig(t, "p", map[string]string{"URL": "$HOST/x"}, nil, true)
	withGlobalConfig(t, path)
	t.Setenv("HOST", "h")
	var out bytes.Buffer
	if err := runDotenv(&out, "", "", false, false, nil); err != nil {
		t.Fatalf("runDotenv: %v", err)
	}
	if !strings.Contains(out.String(), "$HOST/x") || strings.Contains(out.String(), "h/x") {
		t.Errorf("dotenv should not expand $HOST; got:\n%s", out.String())
	}
}

// TestRunDotenvIncludesUnsets pins the wiring end to end: the command feeds
// the resolved tombstones into Format, so the produced document carries the
// commented unset rows with their attribution.
func TestRunDotenvIncludesUnsets(t *testing.T) {
	path := filepath.Join(t.TempDir(), "config.yaml")
	if err := config.WriteProfile(path, "base", config.Profile{Env: map[string]string{"DEBUG": "0", "PORT": "9000"}}, false, false); err != nil {
		t.Fatalf("WriteProfile base: %v", err)
	}
	if err := config.WriteProfile(path, "prod", config.Profile{
		Extends: config.Extends{"base"},
		Unset:   config.Unsets{"DEBUG"},
		Env:     map[string]string{"PORT": "8080"},
	}, true, false); err != nil {
		t.Fatalf("WriteProfile prod: %v", err)
	}
	withGlobalConfig(t, path)

	var out bytes.Buffer
	if err := runDotenv(&out, "prod", "", false, false, nil); err != nil {
		t.Fatalf("runDotenv: %v", err)
	}
	s := out.String()
	if !strings.Contains(s, "# DEBUG=  # unset by \"prod\"") {
		t.Errorf("dotenv output missing commented unset:\n%s", s)
	}
	if !strings.Contains(s, "PORT=8080") {
		t.Errorf("dotenv output lost the live key:\n%s", s)
	}
}

// TestWriteDotenvFileCountsUnsetRows pins that the confirmation counts what
// the document carries: the ", N unset" suffix appears only when tombstone
// rows were written, so the reported numbers match the file.
func TestWriteDotenvFileCountsUnsetRows(t *testing.T) {
	path := filepath.Join(t.TempDir(), "leaf.env")
	var out bytes.Buffer
	if err := writeDotenvFile(&out, path, []byte("B=2\n# A=  # unset by \"mid\"\n"), false, nil, 1, 1); err != nil {
		t.Fatalf("writeDotenvFile: %v", err)
	}
	if !strings.Contains(out.String(), "✓ wrote leaf.env (1 vars, 1 unset)") {
		t.Errorf("confirmation must count unset rows:\n%s", out.String())
	}

	var plain bytes.Buffer
	if err := writeDotenvFile(&plain, filepath.Join(t.TempDir(), "p.env"), []byte("A=1\n"), false, nil, 1, 0); err != nil {
		t.Fatalf("writeDotenvFile: %v", err)
	}
	if s := plain.String(); strings.Contains(s, "unset") {
		t.Errorf("plain profile confirmation must stay unchanged:\n%s", s)
	}
}
