// Package dotenv renders enver profiles as .env documents and (in a future
// iteration) parses them back. The format aims for broad compatibility with
// common dotenv consumers while round-tripping cleanly through enver itself.
package dotenv

import (
	"sort"
	"strings"
)

// needsQuote reports whether v must be single-quoted in a .env file. A value is
// safe bare only when it is non-empty and free of whitespace, comment/start/hash
// metacharacters, quotes, backslashes, dollar signs, and control characters.
func needsQuote(v string) bool {
	if v == "" {
		return true
	}
	for _, r := range v {
		if r < 0x20 || r == 0x7f { // control chars: \t \n \r DEL, etc.
			return true
		}
		switch r {
		case ' ', '#', '=', '\'', '"', '\\', '`', '$':
			return true
		}
	}
	return false
}

// quote wraps v in single quotes (literal — no $VAR expansion) and escapes any
// embedded single quote using the POSIX backslash sequence, matching enver's
// existing export quoting so enver's own outputs stay internally consistent.
func quote(v string) string {
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
}

// formatExpandable emits a value containing $ as a dotenvx double-quoted string:
// $$ becomes \$ (literal $ in double quotes), \ and " are escaped, and $VAR/${...}
// are left intact so the consumer expands them. This is the reverse of Parse's
// double-quote bridge, making dotenv output round-trip through import.
func formatExpandable(v string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(v); i++ {
		c := v[i]
		switch c {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '$':
			if i+1 < len(v) && v[i+1] == '$' {
				b.WriteString(`\$`)
				i++
			} else {
				b.WriteByte('$')
			}
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// Options controls .env rendering.
type Options struct {
	Header  bool     // emit the 2-line origin/secrets header
	Profile string   // profile name, for the header
	Chain   []string // resolved extends chain (name → … → root), for the header
}

// Format renders env as a .env document. Keys are sorted for stable output.
// When opts.Header is set, a 2-line header precedes the variables. For each key
// present in comments, the comment is emitted as "# "-prefixed line(s) above the
// variable; keys without a comment produce no comment line. Values are bare when
// safe and single-quoted otherwise. Format performs no I/O.
func Format(env map[string]string, comments map[string]string, opts Options) []byte {
	var b strings.Builder
	if opts.Header {
		b.WriteString("# Generated by enver from profile \"" + opts.Profile + "\"\n")
		b.WriteString("# Chain: " + strings.Join(opts.Chain, " → ") +
			". Values decrypted — do not commit this file.\n\n")
	}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString(formatComment(comments[k]))
		if strings.Contains(env[k], "$") {
			b.WriteString(k + "=" + formatExpandable(env[k]) + "\n")
			continue
		}
		if needsQuote(env[k]) {
			b.WriteString(k + "=" + quote(env[k]) + "\n")
		} else {
			b.WriteString(k + "=" + env[k] + "\n")
		}
	}
	return []byte(b.String())
}

// formatComment normalizes a stored comment into "# "-prefixed line(s). Each line
// has any leading "#" (and surrounding spaces) stripped before re-prefixing, so
// output is uniform regardless of how the YAML node tree stored the prefixes —
// notably the multi-line case where ResolveComments strips only the first line.
// Returns "" when the comment is empty, so callers can always append the result.
func formatComment(c string) string {
	c = strings.TrimSpace(c)
	if c == "" {
		return ""
	}
	var b strings.Builder
	for _, line := range strings.Split(c, "\n") {
		line = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "#"))
		if line == "" {
			b.WriteString("#\n")
			continue
		}
		b.WriteString("# " + line + "\n")
	}
	return b.String()
}
