package dotenv

import (
	"testing"
)

func TestNeedsQuote(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		{"", true}, // empty
		{"plain", false},
		{"db.example.com", false},
		{"sk-live-xxxx", false},
		{"a/b:c@d", false},
		{"redis://localhost:6379", false},
		{"has space", true},
		{"tab\there", true},
		{"new\nline", true},
		{"has#hash", true},
		{"key=val", true},
		{"dollar$var", true},
		{"single'quote", true},
		{"double\"quote", true},
		{"back\\slash", true},
		{"tick`here", true},
		{"lead space", true},
		{"trail space ", true},
		{"del\x7fchar", true},
	}
	for _, c := range cases {
		if got := needsQuote(c.in); got != c.want {
			t.Errorf("needsQuote(%q) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestFormatPlain(t *testing.T) {
	got := string(Format(
		map[string]string{"DB_HOST": "db.example.com", "API_TOKEN": "sk-live"},
		nil,
		Options{Header: false},
	))
	want := "API_TOKEN=sk-live\nDB_HOST=db.example.com\n"
	if got != want {
		t.Errorf("Format plain:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestFormatQuoting(t *testing.T) {
	got := string(Format(
		map[string]string{"APP_NAME": "My App", "GREETING": "Cost: $5", "EMPTY": ""},
		nil, Options{Header: false},
	))
	want := "APP_NAME=\"My App\"\nEMPTY=\"\"\nGREETING=\"Cost: $5\"\n"
	if got != want {
		t.Errorf("Format quoting:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestFormatHeader(t *testing.T) {
	got := string(Format(
		map[string]string{"A": "1"},
		nil,
		Options{Header: true, Profile: "prod", Chain: []string{"prod", "base"}},
	))
	want := "# Generated by enver from profile \"prod\"\n" +
		"# Chain: prod → base. Values decrypted — do not commit this file.\n\n" +
		"A=1\n"
	if got != want {
		t.Errorf("Format header:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestFormatComments(t *testing.T) {
	got := string(Format(
		map[string]string{"DB_HOST": "db.example.com", "CACHE_TTL": "300"},
		map[string]string{"DB_HOST": "Primary database host"},
		Options{Header: false},
	))
	want := "CACHE_TTL=300\n# Primary database host\nDB_HOST=db.example.com\n"
	if got != want {
		t.Errorf("Format comments:\ngot:  %q\nwant: %q", got, want)
	}
}

// TestFormatMultilineComment covers the YAML quirk where ResolveComments strips
// only the first line's "# " prefix: a multi-line HeadComment arrives as
// "line one\n# line two". Format must re-prefix every line uniformly.
func TestFormatMultilineComment(t *testing.T) {
	got := string(Format(
		map[string]string{"A": "1"},
		map[string]string{"A": "line one\n# line two"},
		Options{Header: false},
	))
	want := "# line one\n# line two\nA=1\n"
	if got != want {
		t.Errorf("Format multiline comment:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestFormatMultilineValue(t *testing.T) {
	got := string(Format(
		map[string]string{"MULTI": "line1\nline2"},
		nil,
		Options{Header: false},
	))
	want := "MULTI=\"line1\nline2\"\n"
	if got != want {
		t.Errorf("Format multiline value:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestFormatEmptyEnv(t *testing.T) {
	if got := string(Format(nil, nil, Options{Header: false})); got != "" {
		t.Errorf("empty env, no header = %q, want empty", got)
	}
	got := string(Format(nil, nil, Options{Header: true, Profile: "p", Chain: []string{"p"}}))
	want := "# Generated by enver from profile \"p\"\n" +
		"# Chain: p. Values decrypted — do not commit this file.\n\n"
	if got != want {
		t.Errorf("empty env, header:\ngot:  %q\nwant: %q", got, want)
	}
}

func TestFormatExpansionBridge(t *testing.T) {
	// $-values double-quoted: $$ -> \$, $VAR left intact; no-$ value stays bare/quoted.
	got := string(Format(
		map[string]string{
			"URL":   "postgres://$HOST/db",
			"COST":  "price$$5",
			"MIX":   "$A and $$B",
			"PLAIN": "hello",
		},
		nil, Options{Header: false},
	))
	want := "COST=\"price\\$5\"\n" +
		"MIX=\"$A and \\$B\"\n" +
		"PLAIN=hello\n" +
		"URL=\"postgres://$HOST/db\"\n"
	if got != want {
		t.Errorf("Format bridge:\ngot:  %q\nwant: %q", got, want)
	}
}

// TestFormatRoundTripApostrophe is a regression test for I-1: ensures values with
// apostrophes round-trip correctly through Format->Parse (no data loss).
func TestFormatRoundTripApostrophe(t *testing.T) {
	env := map[string]string{
		"BAKERY":  "Bob's Bakery",
		"QUOTE":   `He said "hello"`,
		"COMPLEX": `It's "awesome"`,
	}
	out := Format(env, nil, Options{Header: false})
	got, err := Parse(out)
	if err != nil {
		t.Fatal(err)
	}
	back := map[string]string{}
	for _, e := range got {
		back[e.Key] = e.Value
	}
	for k, v := range env {
		if back[k] != v {
			t.Errorf("round-trip %s: got %q, want %q", k, back[k], v)
		}
	}
}

// TestParseInlineCommentSpace covers M1: dotenvx behavior where `KEY= # comment`
// (with space) is an empty value with inline comment, but `KEY=#literal` (no space)
// is the literal value `#literal`.
func TestParseInlineCommentSpace(t *testing.T) {
	cases := []struct {
		in   string
		key  string
		want string
	}{
		{"KEY= # comment", "KEY", ""},
		{"KEY=#literal", "KEY", "#literal"},
		{"KEY=  # multi-space comment", "KEY", ""},
		{"KEY=\t#tab-comment", "KEY", ""},
	}
	for _, c := range cases {
		got, err := Parse([]byte(c.in))
		if err != nil {
			t.Fatalf("Parse(%q): %v", c.in, err)
		}
		if len(got) != 1 {
			t.Fatalf("Parse(%q): got %d entries, want 1", c.in, len(got))
		}
		if got[0].Key != c.key {
			t.Errorf("Parse(%q): key = %q, want %q", c.in, got[0].Key, c.key)
		}
		if got[0].Value != c.want {
			t.Errorf("Parse(%q): value = %q, want %q", c.in, got[0].Value, c.want)
		}
	}
}

func TestFormatRoundTripThroughParse(t *testing.T) {
	env := map[string]string{"URL": "postgres://$HOST/db", "COST": "price$$5", "PLAIN": "hi"}
	out := Format(env, nil, Options{Header: false})
	got, err := Parse(out)
	if err != nil {
		t.Fatal(err)
	}
	back := map[string]string{}
	for _, e := range got {
		back[e.Key] = e.Value
	}
	for k, v := range env {
		if back[k] != v {
			t.Errorf("round-trip %s: got %q, want %q", k, back[k], v)
		}
	}
}
