package dotenv

import (
	"reflect"
	"testing"
)

func TestParseBasicAndQuotes(t *testing.T) {
	in := []byte("PLAIN=hello\n" +
		"SINGLE='two $literal lines'\n" + // single $ literal -> bridged to $$
		"DOUBLE=\"x\\ty\"\n" +
		"BACK=`raw $\ntext`\n")
	got, _, err := Parse(in)
	if err != nil {
		t.Fatal(err)
	}
	want := []Entry{
		{Key: "PLAIN", Value: "hello"},
		{Key: "SINGLE", Value: "two $$literal lines"}, // single $ bridged to $$
		{Key: "DOUBLE", Value: "x\ty"},                // \t escape processed (double)
		{Key: "BACK", Value: "raw $$\ntext"},          // backtick: $ -> $$, newline kept
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Parse:\ngot  %+v\nwant %+v", got, want)
	}
}

func TestParseBridge(t *testing.T) {
	// single $ -> $$ (literal for resolve); double \$ -> $$; double $VAR intact.
	got, _, _ := Parse([]byte("A='$x'\nB=\"$x and \\$y\"\n"))
	if got[0].Value != "$$x" {
		t.Errorf("single $ bridge: got %q, want $$x", got[0].Value)
	}
	if got[1].Value != "$x and $$y" {
		t.Errorf("double bridge: got %q, want \"$x and $$y\"", got[1].Value)
	}
}

func TestParseInlineComments(t *testing.T) {
	got, _, _ := Parse([]byte("A=val # c\nB=val#x\nC=\"v # not a comment\"\n"))
	if got[0].Value != "val" {
		t.Errorf("inline stripped: got %q", got[0].Value)
	}
	if got[1].Value != "val#x" {
		t.Errorf("no-space hash kept: got %q", got[1].Value)
	}
	if got[2].Value != "v # not a comment" {
		t.Errorf("quoted hash kept: got %q", got[2].Value)
	}
}

func TestParseCommentsAttachAndHeaderDropped(t *testing.T) {
	in := []byte("# Generated by enver from profile \"p\"\n" +
		"# Chain: p. Values decrypted.\n\n" + // blank -> header dropped
		"# the key comment\nK=v\n")
	got, _, _ := Parse(in)
	if len(got) != 1 || got[0].Key != "K" || got[0].Comment != "the key comment" {
		t.Errorf("comment association: %+v", got)
	}
}

func TestParseExportPrefixAndSkip(t *testing.T) {
	got, _, _ := Parse([]byte("export A=1\n2BAD=x\nNOEQ\nB=2\n"))
	if len(got) != 2 || got[0].Key != "A" || got[0].Value != "1" || got[1].Key != "B" {
		t.Errorf("export-strip + skip-invalid: %+v", got)
	}
}

func TestParseReportsSkippedLines(t *testing.T) {
	data := []byte("GOOD=1\nbad-name=2\nno equals sign\n# comment\nALSO=3\n")
	entries, skips, err := Parse(data)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(entries) != 2 || entries[0].Key != "GOOD" || entries[1].Key != "ALSO" {
		t.Fatalf("entries = %v", entries)
	}
	want := []Skip{{Line: 2, Reason: "invalid key name"}, {Line: 3, Reason: "missing ="}}
	if len(skips) != 2 || skips[0] != want[0] || skips[1] != want[1] {
		t.Fatalf("skips = %v, want %v", skips, want)
	}
}

// TestParseTombstoneRecognizer pins the grammar: exactly enver's row shape
// qualifies, near-miss comments do not.
func TestParseTombstoneRecognizer(t *testing.T) {
	if k, ok := parseTombstone(`# DEBUG=  # unset by "prod"`); !ok || k != "DEBUG" {
		t.Errorf("exact row: got (%q, %v)", k, ok)
	}
	if k, ok := parseTombstone(`#DEBUG=  # unset by "prod"`); !ok || k != "DEBUG" {
		t.Errorf("no space after #: got (%q, %v)", k, ok)
	}
	if k, ok := parseTombstone(`# A=  # unset by "pr\"of"`); !ok || k != "A" {
		t.Errorf("escaped quote: got (%q, %v)", k, ok)
	}
	for _, line := range []string{
		`# DEBUG= some note`,         // not an unset attribution
		`# DEBUG= # unset by "prod"`, // one space, not two
		`# DEBUG=  # unset by prod`,  // unquoted profile
		`# DEBUG=  # unset by "prod`, // unterminated quote
		`# 1BAD=  # unset by "prod"`, // invalid key
	} {
		if _, ok := parseTombstone(line); ok {
			t.Errorf("parseTombstone(%q) accepted a near-miss", line)
		}
	}
}

// TestParseDropsTombstones pins that enver's own unset rows re-import as
// nothing, and that neighboring comments still attach across the gap.
func TestParseDropsTombstones(t *testing.T) {
	in := tombstoneRow("DEBUG", "mid") +
		"# real comment\nPORT=8080\n" +
		tombstoneRow("TRACE", "prod") +
		"\nA=1\n" +
		tombstoneRow("VERBOSE", "leaf") +
		"B=2\n"
	got, _, err := Parse([]byte(in))
	if err != nil {
		t.Fatal(err)
	}
	want := []Entry{
		{Key: "PORT", Value: "8080", Comment: "real comment"},
		{Key: "A", Value: "1"},
		{Key: "B", Value: "2"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("tombstone drop:\ngot  %+v\nwant %+v", got, want)
	}
}
