package dotenv

import (
	"reflect"
	"testing"
)

func TestParseBasicAndQuotes(t *testing.T) {
	in := []byte("PLAIN=hello\n" +
		"SINGLE='two $literal lines'\n" + // single $ literal -> bridged to $$
		"DOUBLE=\"x\\ty\"\n" +
		"BACK=`raw $\ntext`\n")
	got, err := Parse(in)
	if err != nil {
		t.Fatal(err)
	}
	want := []Entry{
		{Key: "PLAIN", Value: "hello"},
		{Key: "SINGLE", Value: "two $$literal lines"}, // single $ bridged to $$
		{Key: "DOUBLE", Value: "x\ty"},                // \t escape processed (double)
		{Key: "BACK", Value: "raw $$\ntext"},          // backtick: $ -> $$, newline kept
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Parse:\ngot  %+v\nwant %+v", got, want)
	}
}

func TestParseBridge(t *testing.T) {
	// single $ -> $$ (literal for resolve); double \$ -> $$; double $VAR intact.
	got, _ := Parse([]byte("A='$x'\nB=\"$x and \\$y\"\n"))
	if got[0].Value != "$$x" {
		t.Errorf("single $ bridge: got %q, want $$x", got[0].Value)
	}
	if got[1].Value != "$x and $$y" {
		t.Errorf("double bridge: got %q, want \"$x and $$y\"", got[1].Value)
	}
}

func TestParseInlineComments(t *testing.T) {
	got, _ := Parse([]byte("A=val # c\nB=val#x\nC=\"v # not a comment\"\n"))
	if got[0].Value != "val" {
		t.Errorf("inline stripped: got %q", got[0].Value)
	}
	if got[1].Value != "val#x" {
		t.Errorf("no-space hash kept: got %q", got[1].Value)
	}
	if got[2].Value != "v # not a comment" {
		t.Errorf("quoted hash kept: got %q", got[2].Value)
	}
}

func TestParseCommentsAttachAndHeaderDropped(t *testing.T) {
	in := []byte("# Generated by enver from profile \"p\"\n" +
		"# Chain: p. Values decrypted.\n\n" + // blank -> header dropped
		"# the key comment\nK=v\n")
	got, _ := Parse(in)
	if len(got) != 1 || got[0].Key != "K" || got[0].Comment != "the key comment" {
		t.Errorf("comment association: %+v", got)
	}
}

func TestParseExportPrefixAndSkip(t *testing.T) {
	got, _ := Parse([]byte("export A=1\n2BAD=x\nNOEQ\nB=2\n"))
	if len(got) != 2 || got[0].Key != "A" || got[0].Value != "1" || got[1].Key != "B" {
		t.Errorf("export-strip + skip-invalid: %+v", got)
	}
}
